import type { NewServiceRecord, ServiceRecord } from '../domain/types';
import { enqueueChange } from '../sync/queue';
import { deleteLocalMedia } from '../media/local';
import { bumpDataVersion,getActiveWorkspace,getDb,newId,nowIso } from './database';
type ServiceRow={id:string;vehicle_id:string;service_type:string;date:string;mileage:number|null;cost:number|null;shop_name:string|null;notes:string|null;receipt_uri:string|null;next_due_date:string|null;next_due_mileage:number|null;created_at:string;updated_at:string};
function fromRow(r:ServiceRow):ServiceRecord{return{id:r.id,vehicleId:r.vehicle_id,serviceType:r.service_type,date:r.date,mileage:r.mileage,cost:r.cost,shopName:r.shop_name,notes:r.notes,receiptUri:r.receipt_uri,nextDueDate:r.next_due_date,nextDueMileage:r.next_due_mileage,createdAt:r.created_at,updatedAt:r.updated_at};}
export function listServiceRecords(vehicleId:string):ServiceRecord[]{return getDb().getAllSync<ServiceRow>('SELECT * FROM service_records WHERE workspace_id=? AND vehicle_id=? AND deleted_at IS NULL ORDER BY date DESC,created_at DESC',[getActiveWorkspace(),vehicleId]).map(fromRow);}
export function listAllServiceRecords():ServiceRecord[]{return getDb().getAllSync<ServiceRow>('SELECT * FROM service_records WHERE workspace_id=? AND deleted_at IS NULL ORDER BY date DESC',[getActiveWorkspace()]).map(fromRow);}
export function getServiceRecord(id:string):ServiceRecord|null{const r=getDb().getFirstSync<ServiceRow>('SELECT * FROM service_records WHERE id=? AND workspace_id=? AND deleted_at IS NULL',[id,getActiveWorkspace()]);return r?fromRow(r):null;}
export function createServiceRecord(input:NewServiceRecord):ServiceRecord{const id=newId(),ts=nowIso(),w=getActiveWorkspace();getDb().runSync(`INSERT INTO service_records(id,workspace_id,vehicle_id,service_type,date,mileage,cost,shop_name,notes,receipt_uri,next_due_date,next_due_mileage,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[id,w,input.vehicleId,input.serviceType,input.date,input.mileage,input.cost,input.shopName,input.notes,input.receiptUri,input.nextDueDate,input.nextDueMileage,ts,ts]);enqueueChange('service_records',id);bumpDataVersion();return{...input,id,createdAt:ts,updatedAt:ts};}
export function updateServiceRecord(id:string,input:NewServiceRecord){const previous=getServiceRecord(id);const ts=nowIso();getDb().runSync(`UPDATE service_records SET vehicle_id=?,service_type=?,date=?,mileage=?,cost=?,shop_name=?,notes=?,receipt_uri=?,next_due_date=?,next_due_mileage=?,updated_at=? WHERE id=? AND workspace_id=?`,[input.vehicleId,input.serviceType,input.date,input.mileage,input.cost,input.shopName,input.notes,input.receiptUri,input.nextDueDate,input.nextDueMileage,ts,id,getActiveWorkspace()]);enqueueChange('service_records',id);if(previous?.receiptUri&&previous.receiptUri!==input.receiptUri)deleteLocalMedia(previous.receiptUri);bumpDataVersion();}
export function deleteServiceRecord(id:string){const previous=getServiceRecord(id);const ts=nowIso();getDb().runSync('UPDATE service_records SET deleted_at=?,updated_at=? WHERE id=? AND workspace_id=?',[ts,ts,id,getActiveWorkspace()]);enqueueChange('service_records',id);deleteLocalMedia(previous?.receiptUri);bumpDataVersion();}
