import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Button, Chip, EmptyState, Field, SectionHeader } from '@/components/ui';
import { useVehicles } from '@/lib/db/hooks';
import { updateVehicleMileage } from '@/lib/db/vehicleRepo';
import { getServiceRecord, updateServiceRecord } from '@/lib/db/serviceRepo';
import { upsertMaintenanceReminder } from '@/lib/db/reminderRepo';
import { isValidIsoDate } from '@/lib/domain/date';
import { SERVICE_TYPES, serviceTypeDef } from '@/lib/domain/serviceTypes';
import { palette, spacing, typography } from '@/lib/theme';
export default function EditServiceScreen(){const{id}=useLocalSearchParams<{id:string}>();const router=useRouter();const record=id?getServiceRecord(id):null;const vehicles=useVehicles();const[vehicleId,setVehicleId]=useState(record?.vehicleId);const[type,setType]=useState(record?.serviceType??'other');const[date,setDate]=useState(record?.date??'');const[mileage,setMileage]=useState(record?.mileage!=null?String(record.mileage):'');const[cost,setCost]=useState(record?.cost!=null?String(record.cost):'');const[shop,setShop]=useState(record?.shopName??'');const[notes,setNotes]=useState(record?.notes??'');const[nextDate,setNextDate]=useState(record?.nextDueDate??'');const[nextMiles,setNextMiles]=useState(record?.nextDueMileage!=null?String(record.nextDueMileage):'');const[error,setError]=useState<string|null>(null);if(!record)return <View style={styles.screen}><EmptyState title="Service record not found" message="It may have been deleted."/></View>;const currentRecord=record;
 function save(){if(!vehicleId||!isValidIsoDate(date)||(nextDate&&!isValidIsoDate(nextDate))){setError('Check service and next-due dates');return;}const mi=mileage?Number(mileage.replace(/[^\d]/g,'')):null,price=cost?Number(cost.replace(/[^\d.]/g,'')):null,dueMiles=nextMiles?Number(nextMiles.replace(/[^\d]/g,'')):null;updateServiceRecord(currentRecord.id,{vehicleId,serviceType:type,date,mileage:mi,cost:price,shopName:shop.trim()||null,notes:notes.trim()||null,receiptUri:currentRecord.receiptUri,nextDueDate:nextDate||null,nextDueMileage:dueMiles});const selectedVehicle=vehicles.find(v=>v.id===vehicleId);if(selectedVehicle&&mi!=null&&mi>selectedVehicle.mileage)updateVehicleMileage(selectedVehicle.id,mi);upsertMaintenanceReminder({vehicleId,title:serviceTypeDef(type).label,category:type,dueDate:nextDate||null,dueMileage:dueMiles});router.back();}
 return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView style={styles.screen} contentContainerStyle={{padding:spacing.screenPadding,paddingBottom:spacing['2xl']}}><SectionHeader title="Vehicle"/><View style={styles.chips}>{vehicles.map(v=><Chip key={v.id} label={v.nickname} selected={v.id===vehicleId} onPress={()=>setVehicleId(v.id)}/>)}</View><SectionHeader title="Service"/><View style={styles.chips}>{SERVICE_TYPES.map(t=><Chip key={t.id} label={t.label} selected={t.id===type} onPress={()=>setType(t.id)}/>)}</View><View style={styles.two}><View style={{flex:1}}><Field label="Date" value={date} onChangeText={setDate}/></View><View style={{flex:1}}><Field label="Mileage" value={mileage} onChangeText={setMileage} keyboardType="number-pad"/></View></View><View style={styles.two}><View style={{flex:1}}><Field label="Cost" value={cost} onChangeText={setCost} keyboardType="decimal-pad"/></View><View style={{flex:1}}><Field label="Shop" value={shop} onChangeText={setShop}/></View></View><Field label="Notes" value={notes} onChangeText={setNotes}/><SectionHeader title="Next due"/><View style={styles.two}><View style={{flex:1}}><Field label="Date" value={nextDate} onChangeText={setNextDate}/></View><View style={{flex:1}}><Field label="Mileage" value={nextMiles} onChangeText={setNextMiles} keyboardType="number-pad"/></View></View>{error&&<Text style={styles.error}>{error}</Text>}<Button title="Save changes" onPress={save}/></ScrollView></KeyboardAvoidingView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:palette.bg.app},chips:{flexDirection:'row',flexWrap:'wrap'},two:{flexDirection:'row',gap:spacing.md},error:{color:palette.status.overdue,fontSize:typography.caption.size,marginBottom:spacing.md}});
