import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Button, Chip, EmptyState, Field, SectionHeader } from '@/components/ui';
import { createFuelEntry } from '@/lib/db/fuelRepo';
import { useVehicles } from '@/lib/db/hooks';
import { updateVehicleMileage } from '@/lib/db/vehicleRepo';
import { isValidIsoDate } from '@/lib/domain/date';
import { todayIso } from '@/lib/domain/due';
import { palette, spacing, typography } from '@/lib/theme';
export default function AddFuelScreen(){const router=useRouter();const params=useLocalSearchParams<{vehicleId?:string}>();const vehicles=useVehicles();const[vehicleId,setVehicleId]=useState(params.vehicleId??vehicles[0]?.id);const vehicle=vehicles.find(v=>v.id===vehicleId);const[date,setDate]=useState(todayIso());const[mileage,setMileage]=useState(vehicle?String(vehicle.mileage):'');const[gallons,setGallons]=useState('');const[totalCost,setTotalCost]=useState('');const[station,setStation]=useState('');const[notes,setNotes]=useState('');const[fullTank,setFullTank]=useState(true);const[error,setError]=useState<string|null>(null);
  function save(){if(!vehicle)return;if(!isValidIsoDate(date)){setError('Enter a real date as YYYY-MM-DD');return;}const mi=Number(mileage.replace(/[^\d]/g,'')),gal=Number(gallons.replace(/[^\d.]/g,'')),cost=Number(totalCost.replace(/[^\d.]/g,''));if(!Number.isFinite(mi)||mi<0){setError('Mileage is required');return;}if(!Number.isFinite(gal)||gal<=0){setError('Gallons must be greater than 0');return;}if(!Number.isFinite(cost)||cost<0){setError('Total cost must be 0 or greater');return;}createFuelEntry({vehicleId:vehicle.id,date,mileage:mi,gallons:gal,totalCost:cost,station:station.trim()||null,notes:notes.trim()||null,fullTank});if(mi>vehicle.mileage)updateVehicleMileage(vehicle.id,mi);router.back();}
  if(!vehicles.length)return <View style={styles.screen}><EmptyState title="No vehicles" message="Add a vehicle before logging fuel."/></View>;
  return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView style={styles.screen} contentContainerStyle={{padding:spacing.screenPadding,paddingBottom:spacing['2xl']}} keyboardShouldPersistTaps="handled">{vehicles.length>1&&<><SectionHeader title="Vehicle"/><View style={styles.chips}>{vehicles.map(v=><Chip key={v.id} label={v.nickname} selected={v.id===vehicleId} onPress={()=>{setVehicleId(v.id);setMileage(String(v.mileage));}}/>)}</View></>}<SectionHeader title="Fill-up"/><View style={styles.two}><View style={{flex:1}}><Field label="Date" value={date} onChangeText={setDate} placeholder="YYYY-MM-DD"/></View><View style={{flex:1}}><Field label="Odometer" value={mileage} onChangeText={setMileage} keyboardType="number-pad" placeholder="82000"/></View></View><View style={styles.two}><View style={{flex:1}}><Field label="Gallons" value={gallons} onChangeText={setGallons} keyboardType="decimal-pad" placeholder="10.4"/></View><View style={{flex:1}}><Field label="Total paid" value={totalCost} onChangeText={setTotalCost} keyboardType="decimal-pad" placeholder="45.20"/></View></View><Field label="Station (optional)" value={station} onChangeText={setStation} placeholder="Shell"/><Field label="Notes (optional)" value={notes} onChangeText={setNotes} placeholder="Premium, road trip…"/><SectionHeader title="Tank"/><View style={styles.chips}><Chip label="Filled up" selected={fullTank} onPress={()=>setFullTank(true)}/><Chip label="Partial fill" selected={!fullTank} onPress={()=>setFullTank(false)}/></View>{gallons&&totalCost&&Number(gallons)>0&&<Text style={styles.hint}>{(Number(totalCost)/Number(gallons)).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:3})} / gal</Text>}{error&&<Text style={styles.error}>{error}</Text>}<Button title="Save fuel" onPress={save} style={{marginTop:spacing.md}}/></ScrollView></KeyboardAvoidingView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:palette.bg.app},chips:{flexDirection:'row',flexWrap:'wrap'},two:{flexDirection:'row',gap:spacing.md},hint:{color:palette.text.secondary,fontSize:typography.body.size,marginBottom:spacing.md},error:{color:palette.status.overdue,fontSize:typography.caption.size,marginTop:spacing.md}});
