import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Button, Chip, EmptyState, Field, SectionHeader } from '@/components/ui';
import { getFuelEntry, updateFuelEntry } from '@/lib/db/fuelRepo';
import { useVehicles } from '@/lib/db/hooks';
import { updateVehicleMileage } from '@/lib/db/vehicleRepo';
import { isValidIsoDate } from '@/lib/domain/date';
import { palette, spacing, typography } from '@/lib/theme';
export default function EditFuelScreen(){const router=useRouter();const{id}=useLocalSearchParams<{id:string}>();const entry=id?getFuelEntry(id):null;const vehicles=useVehicles();const[vehicleId,setVehicleId]=useState(entry?.vehicleId);const[date,setDate]=useState(entry?.date??'');const[mileage,setMileage]=useState(entry?String(entry.mileage):'');const[gallons,setGallons]=useState(entry?String(entry.gallons):'');const[totalCost,setTotalCost]=useState(entry?String(entry.totalCost):'');const[station,setStation]=useState(entry?.station??'');const[notes,setNotes]=useState(entry?.notes??'');const[fullTank,setFullTank]=useState(entry?.fullTank??true);const[error,setError]=useState<string|null>(null);if(!entry)return <View style={styles.screen}><EmptyState title="Fuel entry not found" message="It may have been deleted."/></View>;const currentEntry=entry;
 function save(){if(!vehicleId||!isValidIsoDate(date)){setError('Enter a real date as YYYY-MM-DD');return;}const mi=Number(mileage.replace(/[^\d]/g,'')),gal=Number(gallons.replace(/[^\d.]/g,'')),cost=Number(totalCost.replace(/[^\d.]/g,''));if(!Number.isFinite(mi)||mi<0||!Number.isFinite(gal)||gal<=0||!Number.isFinite(cost)||cost<0){setError('Check mileage, gallons, and total cost');return;}updateFuelEntry(currentEntry.id,{vehicleId,date,mileage:mi,gallons:gal,totalCost:cost,station:station.trim()||null,notes:notes.trim()||null,fullTank});const selectedVehicle=vehicles.find(v=>v.id===vehicleId);if(selectedVehicle&&mi>selectedVehicle.mileage)updateVehicleMileage(selectedVehicle.id,mi);router.back();}
 return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView style={styles.screen} contentContainerStyle={{padding:spacing.screenPadding,paddingBottom:spacing['2xl']}}><SectionHeader title="Vehicle"/><View style={styles.chips}>{vehicles.map(v=><Chip key={v.id} label={v.nickname} selected={v.id===vehicleId} onPress={()=>setVehicleId(v.id)}/>)}</View><SectionHeader title="Fill-up"/><View style={styles.two}><View style={{flex:1}}><Field label="Date" value={date} onChangeText={setDate}/></View><View style={{flex:1}}><Field label="Odometer" value={mileage} onChangeText={setMileage} keyboardType="number-pad"/></View></View><View style={styles.two}><View style={{flex:1}}><Field label="Gallons" value={gallons} onChangeText={setGallons} keyboardType="decimal-pad"/></View><View style={{flex:1}}><Field label="Total paid" value={totalCost} onChangeText={setTotalCost} keyboardType="decimal-pad"/></View></View><Field label="Station" value={station} onChangeText={setStation}/><Field label="Notes" value={notes} onChangeText={setNotes}/><View style={styles.chips}><Chip label="Filled up" selected={fullTank} onPress={()=>setFullTank(true)}/><Chip label="Partial fill" selected={!fullTank} onPress={()=>setFullTank(false)}/></View>{error&&<Text style={styles.error}>{error}</Text>}<Button title="Save changes" onPress={save} style={{marginTop:spacing.lg}}/></ScrollView></KeyboardAvoidingView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:palette.bg.app},chips:{flexDirection:'row',flexWrap:'wrap'},two:{flexDirection:'row',gap:spacing.md},error:{color:palette.status.overdue,fontSize:typography.caption.size,marginTop:spacing.md}});
