import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Button, Chip, EmptyState, Field, SectionHeader } from '@/components/ui';
import { useVehicles } from '@/lib/db/hooks';
import { getReminder, updateReminder } from '@/lib/db/reminderRepo';
import { isValidIsoDate } from '@/lib/domain/date';
import type { RecurrenceType } from '@/lib/domain/types';
import { palette, spacing, typography } from '@/lib/theme';
const OPTIONS:Array<{id:RecurrenceType;label:string}>=[{id:'none',label:'One time'},{id:'date',label:'By time'},{id:'mileage',label:'By miles'},{id:'both',label:'Time or miles'}];
export default function EditReminderScreen(){const{id}=useLocalSearchParams<{id:string}>();const router=useRouter();const reminder=id?getReminder(id):null;const vehicles=useVehicles();const[vehicleId,setVehicleId]=useState(reminder?.vehicleId);const[title,setTitle]=useState(reminder?.title??'');const[category,setCategory]=useState(reminder?.category??'other');const[dueDate,setDueDate]=useState(reminder?.dueDate??'');const[dueMileage,setDueMileage]=useState(reminder?.dueMileage!=null?String(reminder.dueMileage):'');const[recurrence,setRecurrence]=useState<RecurrenceType>(reminder?.recurrenceType??'none');const[months,setMonths]=useState(reminder?.recurrenceIntervalMonths!=null?String(reminder.recurrenceIntervalMonths):'');const[miles,setMiles]=useState(reminder?.recurrenceIntervalMiles!=null?String(reminder.recurrenceIntervalMiles):'');const[error,setError]=useState<string|null>(null);if(!reminder)return <View style={styles.screen}><EmptyState title="Reminder not found" message="It may have been deleted."/></View>;const currentReminder=reminder;
 function save(){if(!vehicleId||!title.trim()){setError('Vehicle and title are required');return;}if(dueDate&&!isValidIsoDate(dueDate)){setError('Due date must be a real YYYY-MM-DD date');return;}if(!dueDate&&!dueMileage){setError('Set a due date, mileage, or both');return;}const wantsDate=recurrence==='date'||recurrence==='both',wantsMiles=recurrence==='mileage'||recurrence==='both';if(wantsDate&&!months){setError('Set repeat months');return;}if(wantsMiles&&!miles){setError('Set repeat miles');return;}updateReminder(currentReminder.id,{vehicleId,title:title.trim(),category,dueDate:dueDate||null,dueMileage:dueMileage?Number(dueMileage.replace(/[^\d]/g,'')):null,recurrenceType:recurrence,recurrenceIntervalMonths:wantsDate?Number(months):null,recurrenceIntervalMiles:wantsMiles?Number(miles.replace(/[^\d]/g,'')):null});router.back();}
 return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView style={styles.screen} contentContainerStyle={{padding:spacing.screenPadding,paddingBottom:spacing['2xl']}}><SectionHeader title="Vehicle"/><View style={styles.chips}>{vehicles.map(v=><Chip key={v.id} label={v.nickname} selected={v.id===vehicleId} onPress={()=>setVehicleId(v.id)}/>)}</View><Field label="Title" value={title} onChangeText={setTitle}/><Field label="Category" value={category} onChangeText={setCategory}/><View style={styles.two}><View style={{flex:1}}><Field label="Due date" value={dueDate} onChangeText={setDueDate}/></View><View style={{flex:1}}><Field label="Due mileage" value={dueMileage} onChangeText={setDueMileage} keyboardType="number-pad"/></View></View><SectionHeader title="Repeats"/><View style={styles.chips}>{OPTIONS.map(o=><Chip key={o.id} label={o.label} selected={o.id===recurrence} onPress={()=>setRecurrence(o.id)}/>)}</View>{(recurrence==='date'||recurrence==='both')&&<Field label="Every N months" value={months} onChangeText={setMonths} keyboardType="number-pad"/>}{(recurrence==='mileage'||recurrence==='both')&&<Field label="Every N miles" value={miles} onChangeText={setMiles} keyboardType="number-pad"/>}{error&&<Text style={styles.error}>{error}</Text>}<Button title="Save changes" onPress={save}/></ScrollView></KeyboardAvoidingView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:palette.bg.app},chips:{flexDirection:'row',flexWrap:'wrap'},two:{flexDirection:'row',gap:spacing.md},error:{color:palette.status.overdue,fontSize:typography.caption.size,marginBottom:spacing.md}});
