import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React, { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { PurchasesPackage } from 'react-native-purchases';
import { Button, Card, Screen } from '@/components/ui';
import { PRO_FEATURES } from '@/lib/monetization/entitlements';
import { useEntitlements } from '@/lib/monetization/purchases';
import { palette, radius, spacing, typography } from '@/lib/theme';
const PACKAGE_LABELS:Record<string,string>={$rc_monthly:'Monthly',$rc_annual:'Annual',$rc_lifetime:'Lifetime'};
const packageLabel=(pkg:PurchasesPackage)=>PACKAGE_LABELS[pkg.identifier]??pkg.product.title;
export default function PaywallScreen(){const router=useRouter();const{status,isPro,packages,purchase,restore}=useEntitlements();const[busy,setBusy]=useState<string|null>(null);async function buy(pkg:PurchasesPackage){setBusy(pkg.identifier);try{if(await purchase(pkg)){Alert.alert('Welcome to Pro','Receipt vault, AI repair and quote tools, unlimited vehicles, and ownership reports are unlocked.');router.back();}}catch(e){Alert.alert('Purchase failed',e instanceof Error?e.message:'Try again.');}finally{setBusy(null);}}async function restorePurchases(){setBusy('restore');try{if(await restore()){Alert.alert('Purchases restored','Glovebox Pro is active.');router.back();}else Alert.alert('Nothing to restore','No Glovebox Pro purchase was found for this store account.');}catch(e){Alert.alert('Restore failed',e instanceof Error?e.message:'Try again.');}finally{setBusy(null);}}
 return <Screen style={{padding:0}}><ScrollView contentContainerStyle={{padding:spacing.screenPadding,paddingBottom:spacing['2xl']}}><View style={styles.hero}><View style={styles.heroIcon}><Ionicons name="star" size={28} color={palette.accent.primary}/></View><Text style={styles.heroTitle}>Glovebox Pro</Text><Text style={styles.heroSubtitle}>The free app remembers your car offline. Pro helps you understand the expensive stuff — receipts, repairs, quotes, and proof of ownership history.</Text></View><Card style={{marginTop:spacing.xl}}>{PRO_FEATURES.map((f,i)=><View key={f.title} style={[styles.featureRow,i<PRO_FEATURES.length-1&&styles.featureBorder]}><Ionicons name="checkmark-circle" size={20} color={palette.status.ok}/><View style={{flex:1}}><Text style={styles.featureTitle}>{f.title}</Text><Text style={styles.featureDetail}>{f.detail}</Text></View></View>)}</Card>
 {isPro?<Card style={{marginTop:spacing.xl}}><Text style={styles.active}>Pro is active on this device.</Text></Card>:status==='ready'&&packages.length>0?<View style={{marginTop:spacing.xl,gap:spacing.md}}>{packages.map(pkg=><Pressable key={pkg.identifier} onPress={()=>void buy(pkg)} disabled={busy!==null} style={({pressed})=>[styles.packageCard,pressed&&{opacity:.85},busy!==null&&{opacity:.5}]}><View style={{flex:1}}><Text style={styles.packageLabel}>{packageLabel(pkg)}</Text><Text style={styles.packagePrice}>{pkg.product.priceString}</Text></View><Ionicons name="chevron-forward" size={18} color={palette.text.onAccent}/></Pressable>)}<Button title="Restore purchases" variant="ghost" loading={busy==='restore'} onPress={()=>void restorePurchases()}/><Text style={styles.legal}>Recurring subscriptions renew according to the billing period shown by the store until cancelled in your store account. Lifetime purchases, if offered, are one-time purchases and do not renew.</Text><View style={styles.legalLinks}><Button title="Privacy" variant="ghost" onPress={()=>router.push('/legal/privacy')} style={{flex:1}}/><Button title="Terms" variant="ghost" onPress={()=>router.push('/legal/terms')} style={{flex:1}}/></View></View>:<Card style={{marginTop:spacing.xl}}><Text style={styles.unavailable}>{status==='loading'?'Loading plans…':'Store purchases are not available in this build. The free offline-first core remains usable.'}</Text></Card>}</ScrollView></Screen>;
}
const styles=StyleSheet.create({hero:{alignItems:'center',marginTop:spacing.lg},heroIcon:{width:64,height:64,borderRadius:radius.pill,backgroundColor:palette.bg.surfaceRaised,alignItems:'center',justifyContent:'center'},heroTitle:{color:palette.text.primary,fontSize:typography.h1.size,fontWeight:typography.h1.weight,marginTop:spacing.md},heroSubtitle:{color:palette.text.secondary,fontSize:typography.body.size,textAlign:'center',lineHeight:typography.body.lineHeight,marginTop:spacing.sm},featureRow:{flexDirection:'row',gap:spacing.md,paddingVertical:spacing.md},featureBorder:{borderBottomWidth:1,borderBottomColor:palette.border.subtle},featureTitle:{color:palette.text.primary,fontSize:typography.bodyEmphasis.size,fontWeight:typography.bodyEmphasis.weight},featureDetail:{color:palette.text.secondary,fontSize:typography.caption.size,lineHeight:18,marginTop:2},packageCard:{flexDirection:'row',alignItems:'center',backgroundColor:palette.accent.primary,borderRadius:radius.lg,padding:spacing.lg},packageLabel:{color:palette.text.onAccent,fontSize:typography.bodyEmphasis.size,fontWeight:'700'},packagePrice:{color:palette.text.onAccent,fontSize:typography.h3.size,fontWeight:'700',marginTop:2},legal:{color:palette.text.tertiary,fontSize:typography.caption.size,lineHeight:18,textAlign:'center'},legalLinks:{flexDirection:'row'},active:{color:palette.status.ok,fontSize:typography.body.size,textAlign:'center'},unavailable:{color:palette.text.secondary,fontSize:typography.body.size,textAlign:'center'}});
