import { createClient } from 'npm:@supabase/supabase-js@2';
type Task='scan_receipt'|'explain_repair'|'check_cost';
const SERVICE_TYPE_IDS=['oil_change','tire_rotation','tires','brakes','battery','alignment','transmission','coolant','spark_plugs','air_filter','registration','insurance','smog','repair','other'];
const MODEL=Deno.env.get('OPENAI_MODEL')??'gpt-4o-mini';
const corsHeaders={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,'Content-Type':'application/json'}});
type VehicleContext={year?:number;make?:string;model?:string;mileage?:number};
function vehicleLine(v:VehicleContext|undefined){if(!v)return'an unspecified vehicle';const name=[v.year,v.make,v.model].filter(Boolean).join(' ')||'an unspecified vehicle';return v.mileage?`${name} with ${v.mileage} miles`:name;}
type ChatContent=string|Array<Record<string,unknown>>;
function buildMessages(task:Task,body:Record<string,unknown>):Array<{role:string;content:ChatContent}>{switch(task){case'scan_receipt':{const{imageBase64,mimeType}=body as{imageBase64?:string;mimeType?:string};if(!imageBase64)throw new Error('imageBase64 is required for scan_receipt');if(imageBase64.length>5_000_000)throw new Error('Receipt image is too large');return[{role:'system',content:'You extract structured data from auto-shop receipts. Return JSON only with serviceType, date, cost, shopName, mileage, summary. serviceType must be one of '+JSON.stringify(SERVICE_TYPE_IDS)+' or null. Use YYYY-MM-DD for date. Use null when not clearly present. Never invent values.'},{role:'user',content:[{type:'text',text:'Extract the service record from this receipt.'},{type:'image_url',image_url:{url:`data:${mimeType??'image/jpeg'};base64,${imageBase64}`}}]}];}case'explain_repair':{const{serviceLabel,vehicle,notes}=body as{serviceLabel?:string;vehicle?:VehicleContext;notes?:string};if(!serviceLabel)throw new Error('serviceLabel is required');return[{role:'system',content:"You are a trustworthy mechanic explaining car work to a non-expert. No scare tactics. Return JSON only: summary, whatItIs, urgency ('routine'|'soon'|'urgent'), urgencyWhy, diyDifficulty ('easy'|'moderate'|'pro-only'), questionsForShop (2-4). Never claim to diagnose the vehicle remotely."},{role:'user',content:`Explain "${serviceLabel}" for ${vehicleLine(vehicle)}.${notes?` Owner notes: ${notes}`:''}`}];}case'check_cost':{const{serviceLabel,cost,vehicle,shopName}=body as{serviceLabel?:string;cost?:number;vehicle?:VehicleContext;shopName?:string};if(!serviceLabel||typeof cost!=='number'||!Number.isFinite(cost)||cost<=0)throw new Error('serviceLabel and a positive cost are required');return[{role:'system',content:"Estimate whether a US car-repair quote is broadly reasonable. Be explicit that geography, parts quality, taxes, and actual diagnosis can change pricing. Return JSON only: verdict ('low'|'fair'|'high'), typicalLow, typicalHigh, explanation, tips (1-3)."},{role:'user',content:`Is $${cost} a fair price for "${serviceLabel}" on ${vehicleLine(vehicle)}?${shopName?` Quoted by ${shopName}.`:''}`}];}}}
async function requireUser(req:Request){const url=Deno.env.get('SUPABASE_URL'),anon=Deno.env.get('SUPABASE_ANON_KEY'),auth=req.headers.get('Authorization');if(!url||!anon||!auth)return null;const sb=createClient(url,anon,{global:{headers:{Authorization:auth}}});const{data:{user},error}=await sb.auth.getUser();return error||!user?null:{user,sb};}
async function hasPro(userId:string):Promise<boolean>{const key=Deno.env.get('REVENUECAT_SERVER_API_KEY');if(!key)throw new Error('RevenueCat server entitlement verification is not configured');const res=await fetch(`https://api.revenuecat.com/v1/subscribers/${encodeURIComponent(userId)}`,{headers:{Authorization:`Bearer ${key}`,Accept:'application/json'},signal:AbortSignal.timeout(8000)});if(!res.ok)return false;const data=await res.json();const entitlement=data?.subscriber?.entitlements?.pro;if(!entitlement)return false;const expires=entitlement.expires_date;if(expires==null)return true;const ms=Date.parse(expires);return Number.isFinite(ms)&&ms>Date.now();}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return json({error:'POST only'},405);const openAiKey=Deno.env.get('OPENAI_API_KEY');if(!openAiKey)return json({error:'AI is not configured on the server'},501);const caller=await requireUser(req);if(!caller)return json({error:'Authentication required'},401);try{if(!(await hasPro(caller.user.id)))return json({error:'Glovebox Pro is required for AI tools.'},403);}catch(e){console.error('entitlement verification failed',e instanceof Error?e.message:'unknown');return json({error:'Could not verify Glovebox Pro right now. Try again.'},503);}
  const{data:allowed,error:quotaError}=await caller.sb.rpc('consume_ai_request',{p_limit:20});if(quotaError){console.error('AI quota check failed',quotaError.message);return json({error:'AI usage check failed. Try again.'},503);}if(allowed!==true)return json({error:'AI usage limit reached. Try again later.'},429);
  let raw='';try{raw=await req.text();}catch{return json({error:'Invalid request body'},400);}if(new TextEncoder().encode(raw).byteLength>6_000_000)return json({error:'Request too large'},413);let body:Record<string,unknown>;try{body=JSON.parse(raw);}catch{return json({error:'Invalid JSON body'},400);}const task=body.task as Task;if(!['scan_receipt','explain_repair','check_cost'].includes(task))return json({error:'Unknown task'},400);let messages;try{messages=buildMessages(task,body);}catch(e){return json({error:e instanceof Error?e.message:'Bad request'},400);}
  let upstream:Response;try{upstream=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${openAiKey}`},body:JSON.stringify({model:MODEL,messages,response_format:{type:'json_object'},max_tokens:700}),signal:AbortSignal.timeout(20_000)});}catch(e){console.error('OpenAI transport failed',e instanceof Error?e.message:'unknown');return json({error:'The AI service timed out. Try again.'},504);}if(!upstream.ok){console.error(`OpenAI error ${upstream.status}`);return json({error:'The AI service is unavailable right now. Try again.'},502);}const completion=await upstream.json();const content=completion.choices?.[0]?.message?.content;if(typeof content!=='string')return json({error:'Empty AI response'},502);try{return json({task,result:JSON.parse(content)});}catch{return json({error:'The AI returned an unreadable response. Try again.'},502);}});
