import { Ionicons } from '@expo/vector-icons';
import * as Linking from 'expo-linking';
import { Stack, useLocalSearchParams, useRouter } from 'expo-router';
import React, { useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Button, Card, DueBadge, EmptyState, Screen, SectionHeader, StatTile } from '@/components/ui';
import { deleteFuelEntry } from '@/lib/db/fuelRepo';
import { useFuelEntries, useReminders, useServiceRecords, useVehicle } from '@/lib/db/hooks';
import { completeReminder, deleteReminder } from '@/lib/db/reminderRepo';
import { deleteServiceRecord } from '@/lib/db/serviceRepo';
import { deleteVehicle, updateVehicleMileage, updateVehicleRecalls, updateVehicleVinDecode } from '@/lib/db/vehicleRepo';
import { dueSummary, reminderDueState, todayIso } from '@/lib/domain/due';
import { formatMoney, summarizeExpenses } from '@/lib/domain/expenses';
import { healthScore } from '@/lib/domain/healthScore';
import { serviceTypeLabel } from '@/lib/domain/serviceTypes';
import { decodedVinSummary, recallStatus } from '@/lib/domain/vin';
import { canExportReport } from '@/lib/monetization/entitlements';
import { useIsPro } from '@/lib/monetization/purchases';
import { shareVehicleReport } from '@/lib/report/export';
import { palette, radius, spacing, typography } from '@/lib/theme';
import { checkRecalls, decodeVin, vinAvailability } from '@/lib/vin/client';
const TABS=['Overview','Maintenance','Fuel','Expenses','Reminders'] as const; type Tab=(typeof TABS)[number];
export default function VehicleDetailScreen(){const{id}=useLocalSearchParams<{id:string}>();const router=useRouter();const vehicle=useVehicle(id);const records=useServiceRecords(id);const fuel=useFuelEntries(id);const reminders=useReminders({vehicleId:id,status:'active'});const[tab,setTab]=useState<Tab>('Overview');const[mileageDraft,setMileageDraft]=useState<string|null>(null);const[exporting,setExporting]=useState(false);const[decoding,setDecoding]=useState(false);const[checking,setChecking]=useState(false);const isPro=useIsPro();if(!vehicle)return <Screen><EmptyState title="Vehicle not found" message="It may have been deleted."/></Screen>;const currentVehicle=vehicle;
 const today=todayIso(),health=healthScore({vehicle:currentVehicle,records,reminders,today}),expenses=summarizeExpenses(records,today,fuel),recallState=recallStatus({checkedAt:currentVehicle.recallCheckedAt,recalls:currentVehicle.recalls}),decoded=currentVehicle.vinDecoded?decodedVinSummary(currentVehicle.vinDecoded):null;
 function commitMileage(){if(mileageDraft==null)return;const n=Number(mileageDraft.replace(/[^\d]/g,''));if(Number.isFinite(n)&&n>=0&&n!==currentVehicle.mileage)updateVehicleMileage(currentVehicle.id,n);setMileageDraft(null);}
 async function exportReport(){if(exporting)return;const gate=canExportReport(isPro);if(!gate.allowed){Alert.alert('Glovebox Pro',gate.reason,[{text:'Not now',style:'cancel'},{text:'See Pro',onPress:()=>router.push('/paywall')}]);return;}setExporting(true);try{await shareVehicleReport(currentVehicle,records,reminders,fuel);}catch(e){Alert.alert('Export failed',e instanceof Error?e.message:'Try again.');}finally{setExporting(false);}}
 async function onDecode(){if(!currentVehicle.vin||decoding)return;const a=vinAvailability();if(!a.available){Alert.alert('VIN decode unavailable',a.reason);return;}setDecoding(true);try{const result=await decodeVin(currentVehicle.vin);updateVehicleVinDecode(currentVehicle.id,currentVehicle.vin,result);if(!result.decodable)Alert.alert('Could not decode','The VIN did not return recognizable vehicle data.');}catch(e){Alert.alert('Decode failed',e instanceof Error?e.message:'Try again.');}finally{setDecoding(false);}}
 async function onRecall(){if(checking)return;const a=vinAvailability();if(!a.available){Alert.alert('Recall lookup unavailable',a.reason);return;}const source=currentVehicle.vinDecoded;if(!source?.make||!source.model||!source.modelYear){Alert.alert('Decode VIN first','Recall campaign search needs the decoded year, make, and model.');return;}setChecking(true);try{updateVehicleRecalls(currentVehicle.id,await checkRecalls(source.make,source.model,source.modelYear));}catch(e){Alert.alert('Recall lookup failed',e instanceof Error?e.message:'Try again.');}finally{setChecking(false);}}
 function confirmDelete(){Alert.alert('Delete vehicle',`Delete ${currentVehicle.nickname} and its service, fuel, and reminders?`,[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>{deleteVehicle(currentVehicle.id);router.back();}}]);}
 return <Screen style={{padding:0}}><Stack.Screen options={{title:currentVehicle.nickname}}/><ScrollView contentContainerStyle={{padding:spacing.screenPadding,paddingBottom:spacing['2xl']}}>{currentVehicle.photoUri&&<Image source={{uri:currentVehicle.photoUri}} style={styles.hero}/>}<View style={styles.titleRow}><View style={{flex:1}}><Text style={styles.title}>{currentVehicle.year} {currentVehicle.make} {currentVehicle.model}</Text><Text style={styles.meta}>{currentVehicle.trim??''}</Text></View><Button title="Edit" variant="ghost" onPress={()=>router.push({pathname:'/vehicle/edit',params:{id:currentVehicle.id}})}/></View><View style={styles.tabs}>{TABS.map(t=><Pressable key={t} onPress={()=>setTab(t)} style={[styles.tab,tab===t&&styles.tabActive]}><Text style={[styles.tabText,tab===t&&styles.tabTextActive]}>{t}</Text></Pressable>)}</View>
 {tab==='Overview'&&<><View style={styles.stats}><StatTile label="Health Score" value={String(health.score)} hint={health.label}/><StatTile label="Lifetime spend" value={formatMoney(expenses.lifetimeTotal)}/></View><Text style={styles.healthNote}>Health Score measures maintenance record status — overdue work and record gaps — not mechanical condition or safety.</Text><SectionHeader title="Odometer"/><Card><View style={styles.mileageRow}>{mileageDraft===null?<><Text style={styles.big}>{currentVehicle.mileage.toLocaleString()} mi</Text><Button title="Update" variant="ghost" onPress={()=>setMileageDraft(String(currentVehicle.mileage))}/></>:<><TextInput style={styles.mileageInput} keyboardType="number-pad" value={mileageDraft} onChangeText={setMileageDraft} autoFocus/><Button title="Save" onPress={commitMileage}/></>}</View></Card><SectionHeader title="VIN & recall campaigns"/><Card><DetailRow label="Decoded as" value={decoded??(currentVehicle.vin?'Not decoded yet':'Add a VIN in Edit vehicle')}/><DetailRow label="Campaign search" value={recallState==='unknown'?'Not checked yet':recallState==='none'?`No campaigns found · checked ${currentVehicle.recallCheckedAt?.slice(0,10)??today}`:`${currentVehicle.recalls.length} campaign${currentVehicle.recalls.length===1?'':'s'} found`} last={recallState!=='open'}/>{recallState==='open'&&currentVehicle.recalls.map((r,i)=><View key={r.id} style={[styles.recall,i===currentVehicle.recalls.length-1&&{borderBottomWidth:0}]}><Text style={styles.itemTitle}>{r.component??'Recall campaign'}</Text>{r.summary&&<Text style={styles.itemMeta}>{r.summary}</Text>}{r.remedy&&<Text style={styles.itemMeta}>Remedy: {r.remedy}</Text>}</View>)}</Card><Text style={styles.healthNote}>This lookup searches NHTSA campaigns by year/make/model. It does not prove whether this exact VIN has an unresolved recall. Verify VIN-specific status with NHTSA.</Text><View style={styles.two}><Button title="Decode VIN" variant="secondary" loading={decoding} disabled={!currentVehicle.vin} onPress={()=>void onDecode()} style={{flex:1}}/><Button title="Find campaigns" variant="secondary" loading={checking} onPress={()=>void onRecall()} style={{flex:1}}/></View><Button title="Open NHTSA VIN recall checker" variant="ghost" onPress={()=>void Linking.openURL('https://www.nhtsa.gov/recalls')}/><SectionHeader title="Tools"/><Button title="Ask AI about a repair or quote" variant="secondary" onPress={()=>router.push({pathname:'/ai/assistant',params:{vehicleId:currentVehicle.id}})}/><Button title="Export ownership report" variant="secondary" loading={exporting} onPress={()=>void exportReport()} style={{marginTop:spacing.sm}}/><Button title="Delete vehicle" variant="danger" onPress={confirmDelete} style={{marginTop:spacing.xl}}/></>}
 {tab==='Maintenance'&&<><Button title="Log service" onPress={()=>router.push({pathname:'/service/add',params:{vehicleId:currentVehicle.id}})}/>{records.length===0?<EmptyState title="No service history" message="Log maintenance or a repair to build the car’s memory."/>:<View style={styles.list}>{records.map(r=><Card key={r.id}><View style={styles.row}><View style={{flex:1}}><Text style={styles.itemTitle}>{serviceTypeLabel(r.serviceType)}</Text><Text style={styles.itemMeta}>{r.date}{r.mileage!=null?` · ${r.mileage.toLocaleString()} mi`:''}{r.cost!=null?` · ${formatMoney(r.cost)}`:''}</Text>{r.notes&&<Text style={styles.itemMeta}>{r.notes}</Text>}</View><Button title="Edit" variant="ghost" onPress={()=>router.push({pathname:'/service/edit',params:{id:r.id}})}/></View><Button title="Delete" variant="ghost" onPress={()=>deleteServiceRecord(r.id)}/></Card>)}</View>}</>}
 {tab==='Fuel'&&<><Button title="Log fuel" onPress={()=>router.push({pathname:'/fuel/add',params:{vehicleId:currentVehicle.id}})}/>{fuel.length===0?<EmptyState title="No fuel entries" message="Log a fill-up to include fuel in your ownership cost."/>:<View style={styles.list}>{fuel.map(f=><Card key={f.id}><View style={styles.row}><View style={{flex:1}}><Text style={styles.itemTitle}>{formatMoney(f.totalCost)} · {f.gallons.toFixed(2)} gal</Text><Text style={styles.itemMeta}>{f.date} · {f.mileage.toLocaleString()} mi · {(f.totalCost/f.gallons).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:3})}/gal{f.station?` · ${f.station}`:''}</Text></View><Button title="Edit" variant="ghost" onPress={()=>router.push({pathname:'/fuel/edit',params:{id:f.id}})}/></View><Button title="Delete" variant="ghost" onPress={()=>deleteFuelEntry(f.id)}/></Card>)}</View>}</>}
 {tab==='Expenses'&&<><View style={styles.stats}><StatTile label="This month" value={formatMoney(expenses.monthTotal)}/><StatTile label="This year" value={formatMoney(expenses.yearTotal)}/></View><SectionHeader title="Lifetime"/><Card><DetailRow label="Maintenance" value={formatMoney(expenses.maintenanceTotal)}/><DetailRow label="Repairs" value={formatMoney(expenses.repairTotal)}/><DetailRow label="Fuel" value={formatMoney(expenses.fuelTotal)}/><DetailRow label="Registration & admin" value={formatMoney(expenses.adminTotal)}/><DetailRow label="Total" value={formatMoney(expenses.lifetimeTotal)} last/></Card></>}
 {tab==='Reminders'&&<><Button title="New reminder" onPress={()=>router.push({pathname:'/reminder/add',params:{vehicleId:currentVehicle.id}})}/>{reminders.length===0?<EmptyState title="No active reminders" message="Set a date or mileage target and Glovebox can notify you locally."/>:<View style={styles.list}>{reminders.map(r=>{const state=reminderDueState(r,currentVehicle.mileage,today);return <Card key={r.id}><View style={styles.row}><View style={{flex:1}}><Text style={styles.itemTitle}>{r.title}</Text><Text style={styles.itemMeta}>{dueSummary({dueDate:r.dueDate,dueMileage:r.dueMileage,currentMileage:currentVehicle.mileage,today})}</Text></View><DueBadge state={state}/></View><View style={styles.two}><Button title="Done" variant="secondary" onPress={()=>completeReminder(r,currentVehicle.mileage)} style={{flex:1}}/><Button title="Edit" variant="ghost" onPress={()=>router.push({pathname:'/reminder/edit',params:{id:r.id}})} style={{flex:1}}/><Button title="Delete" variant="ghost" onPress={()=>deleteReminder(r.id)} style={{flex:1}}/></View></Card>})}</View>}</>}
 </ScrollView></Screen>;
}
function DetailRow({label,value,last}:{label:string;value:string;last?:boolean}){return <View style={[styles.detailRow,!last&&styles.border]}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>;}
const styles=StyleSheet.create({hero:{width:'100%',height:190,borderRadius:radius.lg,marginBottom:spacing.md},titleRow:{flexDirection:'row',alignItems:'center'},title:{color:palette.text.primary,fontSize:typography.h2.size,fontWeight:typography.h2.weight},meta:{color:palette.text.tertiary,fontSize:typography.caption.size},tabs:{flexDirection:'row',flexWrap:'wrap',gap:spacing.xs,marginVertical:spacing.lg},tab:{paddingVertical:8,paddingHorizontal:10,borderBottomWidth:2,borderBottomColor:'transparent'},tabActive:{borderBottomColor:palette.accent.primary},tabText:{color:palette.text.tertiary,fontSize:typography.caption.size},tabTextActive:{color:palette.text.primary,fontWeight:'600'},stats:{flexDirection:'row',gap:spacing.md},healthNote:{color:palette.text.tertiary,fontSize:typography.caption.size,lineHeight:18,marginTop:spacing.sm},mileageRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.md},big:{color:palette.text.primary,fontSize:typography.h2.size,fontWeight:typography.h2.weight},mileageInput:{flex:1,borderWidth:1,borderColor:palette.border.default,borderRadius:radius.md,color:palette.text.primary,padding:10,fontSize:typography.h3.size},two:{flexDirection:'row',gap:spacing.sm,marginTop:spacing.md},list:{gap:spacing.sm,marginTop:spacing.lg},row:{flexDirection:'row',alignItems:'center',gap:spacing.sm},itemTitle:{color:palette.text.primary,fontSize:typography.bodyEmphasis.size,fontWeight:typography.bodyEmphasis.weight},itemMeta:{color:palette.text.secondary,fontSize:typography.caption.size,lineHeight:18,marginTop:2},recall:{paddingVertical:spacing.sm,borderBottomWidth:1,borderBottomColor:palette.border.subtle},detailRow:{flexDirection:'row',justifyContent:'space-between',gap:spacing.md,paddingVertical:spacing.sm},border:{borderBottomWidth:1,borderBottomColor:palette.border.subtle},detailLabel:{color:palette.text.secondary,fontSize:typography.body.size},detailValue:{color:palette.text.primary,fontSize:typography.body.size,flex:1,textAlign:'right'}});
