import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Button, EmptyState, Field, SectionHeader } from '@/components/ui';
import { useVehicle } from '@/lib/db/hooks';
import { updateVehicle } from '@/lib/db/vehicleRepo';
import { isValidIsoDate } from '@/lib/domain/date';
import { validateVin } from '@/lib/domain/vin';
import { palette, spacing, typography } from '@/lib/theme';
export default function EditVehicleScreen(){const{id}=useLocalSearchParams<{id:string}>();const router=useRouter();const vehicle=useVehicle(id);const[nickname,setNickname]=useState(vehicle?.nickname??'');const[make,setMake]=useState(vehicle?.make??'');const[model,setModel]=useState(vehicle?.model??'');const[year,setYear]=useState(vehicle?String(vehicle.year):'');const[trim,setTrim]=useState(vehicle?.trim??'');const[vin,setVin]=useState(vehicle?.vin??'');const[plate,setPlate]=useState(vehicle?.licensePlate??'');const[purchaseDate,setPurchaseDate]=useState(vehicle?.purchaseDate??'');const[purchasePrice,setPurchasePrice]=useState(vehicle?.purchasePrice!=null?String(vehicle.purchasePrice):'');const[error,setError]=useState<string|null>(null);if(!vehicle)return <View style={styles.screen}><EmptyState title="Vehicle not found" message="It may have been deleted."/></View>;
 function save(){const y=Number(year);if(!nickname.trim()||!make.trim()||!model.trim()||!Number.isInteger(y)||y<1900||y>2100){setError('Check name, make, model, and year');return;}if(purchaseDate&&!isValidIsoDate(purchaseDate)){setError('Purchase date must be a real YYYY-MM-DD date');return;}const vinText=vin.trim();const check=vinText?validateVin(vinText):null;if(check&&!check.valid){setError(check.reason);return;}updateVehicle(vehicle.id,{nickname:nickname.trim(),make:make.trim(),model:model.trim(),year:y,trim:trim.trim()||null,vin:check?.valid?check.vin:vinText||null,licensePlate:plate.trim()||null,purchaseDate:purchaseDate||null,purchasePrice:purchasePrice?Number(purchasePrice.replace(/[^\d.]/g,'')):null,photoUri:vehicle.photoUri});router.back();}
 return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView style={styles.screen} contentContainerStyle={{padding:spacing.screenPadding,paddingBottom:spacing['2xl']}} keyboardShouldPersistTaps="handled"><SectionHeader title="Vehicle"/><Field label="Nickname" value={nickname} onChangeText={setNickname}/><View style={styles.two}><View style={{flex:1}}><Field label="Make" value={make} onChangeText={setMake}/></View><View style={{flex:1}}><Field label="Model" value={model} onChangeText={setModel}/></View></View><View style={styles.two}><View style={{flex:1}}><Field label="Year" value={year} onChangeText={setYear} keyboardType="number-pad"/></View><View style={{flex:1}}><Field label="Trim" value={trim} onChangeText={setTrim}/></View></View><SectionHeader title="Identification"/><Field label="VIN" value={vin} onChangeText={setVin} autoCapitalize="characters"/><Field label="License plate" value={plate} onChangeText={setPlate} autoCapitalize="characters"/><SectionHeader title="Purchase"/><View style={styles.two}><View style={{flex:1}}><Field label="Date" value={purchaseDate} onChangeText={setPurchaseDate} placeholder="YYYY-MM-DD"/></View><View style={{flex:1}}><Field label="Price" value={purchasePrice} onChangeText={setPurchasePrice} keyboardType="decimal-pad"/></View></View>{error&&<Text style={styles.error}>{error}</Text>}<Button title="Save changes" onPress={save}/></ScrollView></KeyboardAvoidingView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:palette.bg.app},two:{flexDirection:'row',gap:spacing.md},error:{color:palette.status.overdue,fontSize:typography.caption.size,marginBottom:spacing.md}});
